export const SHOW_REVIEWS = false;
export const SHOW_BLOG_IN_NAV = true;
export const FACEBOOK_URL = 'https://www.facebook.com/share/1DRs9wTKtT/?mibextid=wwXIfr';
export const INSTAGRAM_URL = 'https://www.instagram.com/roadieai?igsh=MTgwaXVqYnJrMGRnNQ%3D%3D&utm_source=qr';
export const YOUTUBE_URL = 'https://www.youtube.com/@roadiekorea';
export const TIKTOK_URL = 'https://www.tiktok.com/@roadieai';
export const THREADS_URL = 'https://www.threads.com/@roadieai?igshid=NTc4MTIwNjQ2YQ==';
export const TELEGRAM_DM_URL = 'https://t.me/myanmate';
export const MESSENGER_URL = 'https://m.me/61580519695929';
